export const INSERT_BOOKS_DATA_INTO_STORE = 'INSERT_BOOKS_DATA_INTO_STORE';
export const GET_DATA_FROM_STORE = 'GET_DATA_FROM_STORE';
export const FETCH_DATA_FROM_API = 'FETCH_DATA_FROM_API';
export const SHOW_LOADER_SPINNER = 'SHOW_LOADER_SPINNER';
export const FETCHED_DATA_FROM_THE_API = 'FETCHED_DATA_FROM_THE_API';
export const LOAD_BOOKS_DATA_SUCCESS = 'LOAD_BOOKS_DATA_SUCCESS';

export const LOADING_ICON_STATUS = 'LOADING_ICON_STATUS';